services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/mysql-data:/var/lib/mysql
    networks:
      - spring-microservice

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka_server
    ports:
      - "8761:8761"
    networks:
      - spring-microservice

  auth-service:
    container_name: auth-service
    build:
      context: ./auth_service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: vanben277
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      TOKEN_SECRET: ${TOKEN_SECRET}

  department-service:
    container_name: department-service
    build:
      context: ./department_service
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: vanben277
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  account-service:
    container_name: account-service
    build:
      context: ./account_service
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - eureka-server
    networks:
      - spring-microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservice?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: vanben277
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

networks:
  spring-microservice:
    driver: bridge